import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, CheckCircle2, ClipboardList, FileBarChart, ShieldCheck, WalletCards } from "lucide-react";

const money = (value: number) => new Intl.NumberFormat("en-GH", { style: "currency", currency: "GHS", maximumFractionDigits: 0 }).format(value);
const labels: Record<string, { title: string; intro: string; icon: typeof ClipboardList }> = {
  applications: { title: "Loan applications", intro: "Review borrower requests within your branch authority and workflow stage.", icon: ClipboardList },
  collections: { title: "Collections desk", intro: "Record repayments, spot arrears early, and keep borrower balances traceable.", icon: WalletCards },
  compliance: { title: "Compliance review", intro: "Inspect immutable workflow history and branch-scoped operational activity.", icon: ShieldCheck },
  reports: { title: "Portfolio reporting", intro: "Query-backed portfolio measures built from recorded loan terms and repayments.", icon: FileBarChart },
};

export default function Operations({ section }: { section: keyof typeof labels }) {
  const config = labels[section]; const Icon = config.icon;
  const applications = trpc.loans.list.useQuery(undefined, { enabled: section === "applications", retry: false });
  const repayments = trpc.repayments.list.useQuery(undefined, { enabled: section === "collections", retry: false });
  const audit = trpc.audit.list.useQuery(undefined, { enabled: section === "compliance", retry: false });
  const summary = trpc.reports.summary.useQuery(undefined, { enabled: section === "reports" || section === "compliance", retry: false });
  const rows = applications.data ?? [];
  return <div className="min-h-screen bg-[#f6f8f7] px-4 py-7 text-[#17231f] sm:px-8"><div className="mx-auto max-w-[1180px]"><div className="mb-8 flex items-start justify-between gap-4"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#eaf5ee] px-3 py-1.5 text-xs font-semibold uppercase tracking-[0.16em] text-[#2e6a53]"><Icon className="h-3.5 w-3.5" /> Operations</div><h1 className="font-display text-4xl font-semibold tracking-tight">{config.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#74847b]">{config.intro}</p></div><button className="inline-flex items-center gap-2 rounded-lg bg-[#173e32] px-4 py-2.5 text-sm font-medium text-white shadow-lg shadow-[#173e32]/10">Export view <ArrowUpRight className="h-4 w-4" /></button></div>
  {section === "applications" && <Card className="border-[#e0e9e4] bg-white"><CardHeader><CardTitle className="font-display text-xl">Applications in your review scope</CardTitle></CardHeader><CardContent><div className="space-y-3">{rows.length ? rows.map(({ loan, client }) => <div className="flex items-center justify-between rounded-xl border border-[#edf2ee] p-4" key={loan.id}><div><p className="font-medium">{client?.fullName || `Application #${loan.id}`}</p><p className="mt-1 text-xs text-[#84938b]">{loan.product} · {loan.termMonths} months · {money(Number(loan.principal))}</p></div><Badge variant="outline" className="rounded-full">{loan.status.replace("_", " ")}</Badge></div>) : <Empty text="No applications are available in this branch-scoped view." />}</div></CardContent></Card>}
  {section === "collections" && <><div className="grid gap-4 md:grid-cols-3"><SmallMetric title="Repayments recorded" value={repayments.data ? String(repayments.data.length) : "—"} /><SmallMetric title="Collection activity" value="Live" /><SmallMetric title="Arrears queue" value="Review" /></div><Card className="mt-6 border-[#e0e9e4] bg-white"><CardHeader><CardTitle className="font-display text-xl">Recent repayment records</CardTitle></CardHeader><CardContent><div className="space-y-3">{repayments.data?.length ? repayments.data.map(row => <div className="flex items-center justify-between rounded-xl bg-[#f8faf9] p-4" key={row.id}><div><p className="font-medium">{row.reference}</p><p className="mt-1 text-xs text-[#84938b]">Loan #{row.loanApplicationId} · {new Date(row.paidAt).toLocaleDateString()}</p></div><p className="font-semibold text-[#2e7a5b]">{money(Number(row.amount))}</p></div>) : <Empty text="Repayment records will appear here after Finance records a payment." />}</div></CardContent></Card></>}
  {section === "compliance" && <><div className="grid gap-4 md:grid-cols-3"><SmallMetric title="Audit events" value={audit.data ? String(audit.data.length) : "—"} /><SmallMetric title="Portfolio monitored" value={summary.data ? money(summary.data.portfolio) : "—"} /><SmallMetric title="Source integrity" value="Immutable" /></div><Card className="mt-6 border-[#e0e9e4] bg-white"><CardHeader><CardTitle className="font-display text-xl">Immutable audit trail</CardTitle></CardHeader><CardContent><div className="space-y-3">{audit.data?.length ? audit.data.map(row => <div className="flex gap-3 rounded-xl border border-[#edf2ee] p-4" key={row.id}><CheckCircle2 className="mt-0.5 h-4 w-4 text-[#2e8b62]" /><div><p className="font-medium">{row.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-[#84938b]">{row.reason}</p></div><time className="ml-auto text-xs text-[#9aa9a1]">{new Date(row.createdAt).toLocaleDateString()}</time></div>) : <Empty text="No audit events are available in this branch-scoped view." />}</div></CardContent></Card></>}
  {section === "reports" && <Card className="border-[#e0e9e4] bg-white"><CardHeader><CardTitle className="font-display text-xl">Portfolio report</CardTitle></CardHeader><CardContent><div className="grid gap-5 md:grid-cols-2"><ReportRow title="Active loans" value={summary.data ? String(summary.data.activeLoans) : "—"} /><ReportRow title="Portfolio value" value={summary.data ? money(summary.data.portfolio) : "—"} /><ReportRow title="Collected" value={summary.data ? money(summary.data.collected) : "—"} /><ReportRow title="Arrears to review" value={summary.data ? money(summary.data.arrears) : "—"} /></div><p className="mt-6 border-t border-[#edf2ee] pt-5 text-xs leading-5 text-[#84938b]">All figures are query-backed and derived from recorded loan terms and repayments. The flat 4.5% monthly schedule remains the source of truth for each loan.</p></CardContent></Card>}
 </div></div>;
}
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-[#cfddd5] px-5 py-12 text-center text-sm text-[#84938b]">{text}</div>; }
function SmallMetric({ title, value }: { title: string; value: string }) { return <Card className="border-[#e0e9e4] bg-white"><CardContent className="p-5"><p className="text-xs text-[#84938b]">{title}</p><p className="mt-3 font-display text-3xl font-semibold">{value}</p></CardContent></Card>; }
function ReportRow({ title, value }: { title: string; value: string }) { return <div className="rounded-xl bg-[#f8faf9] p-5"><p className="text-xs text-[#84938b]">{title}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-[#214c3b]">{value}</p></div>; }
